### ISSUE TITLE
Original resolution request

### ISSUE THREAD

**Issue by jaygridley** [iPublikuj/images#4]
Hi, I think there is a problem with generation of original resolution for the source image. During the request the width and height of final image is set to null. Afterwards there is a call to Nette's  Image::resize() and subsequently Image::calculateSize() which will fail with Nette\InvalidArgumentException - At least width or height must be specified. 

In my opinion there should be no resize attempt for original resolution or am I doing something wrong?

**Comment by akadlec** [comment]
Yes there could be some bug. This extension is now under development.
