### ISSUE TITLE
Deprecated filters in nette 2.4+

### ISSUE THREAD

**Issue by Vrtak-CZ** [iPublikuj/images#6]
```
User Deprecated

Invoking filters via $template->getImagesLoaderService($vars) is deprecated, use ($vars|getImagesLoaderService)
```

**Comment by akadlec** [comment]
Yes i know. Right now it is under upgrade to nette 2.4 and php7

**Comment by Vrtak-CZ** [comment]
Do you have any ETA?

**Comment by akadlec** [comment]
It is finished, not commited due to failing router test. Mabye next week.

**Comment by akadlec** [comment]
Try new version. Nette 2.4 compatibility issue is fixed
